import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Habit from '../models/Habit.js';
import ShopItem from '../models/ShopItem.js';

dotenv.config();

const defaultHabits = [
  // --- Looksmaxxing & Grooming ---
  {
    title: 'Daily Sunscreen (SPF 30+)',
    category: 'grooming',
    description: 'Apply broad-spectrum sunscreen every morning to protect against UV damage.',
    benefits: 'Prevents premature aging, wrinkles, sunspots, and significantly reduces the risk of skin cancer. UV rays are the #1 cause of skin aging.',
    howTo: 'Apply two finger-lengths of sunscreen to your face and neck every morning as the last step of your skincare routine, even on cloudy days.',
    difficulty: 'easy',
    icon: '☀️',
  },
  {
    title: 'Double Cleanse at Night',
    category: 'grooming',
    description: 'Wash your face using an oil-based cleanser followed by a water-based one.',
    benefits: 'Thoroughly removes sunscreen, sebum, and pollutants that a single cleanse misses, preventing acne and dull skin.',
    howTo: 'Massage cleansing oil/balm on dry skin for 60 seconds, rinse, then wash with a gentle foaming or hydrating cleanser.',
    difficulty: 'medium',
    icon: '🧼',
  },
  {
    title: 'Proper Tongue Posture (Mewing)',
    category: 'grooming',
    description: 'Rest your entire tongue against the roof of your mouth.',
    benefits: 'Over time, it can help define the jawline, improve facial symmetry, and promote nasal breathing.',
    howTo: 'Say "sing" and hold the tongue position. The tip should be behind the teeth, with the middle and back of the tongue pressing the palate.',
    difficulty: 'hard',
    icon: '👅',
  },
  {
    title: 'Gua Sha / Facial Massage',
    category: 'grooming',
    description: 'Use a Gua Sha stone or fingers to massage the face and drain lymphatic fluid.',
    benefits: 'Reduces morning puffiness, increases blood circulation for a glow, and temporarily sharpens facial contours.',
    howTo: 'Apply facial oil. Gently scrape the Gua Sha tool outwards from the center of your face towards your ears, and down your neck.',
    difficulty: 'medium',
    icon: '🪨',
  },
  {
    title: 'Chew Hard Gum / Mastic Gum',
    category: 'grooming',
    description: 'Chew tough gum for 30-60 minutes daily to hypertrophy the masseter muscles.',
    benefits: 'Widens the lower third of the face, giving a stronger and more masculine/defined jawline.',
    howTo: 'Chew mastic gum or Falim gum evenly on both sides of your mouth to prevent asymmetry. Do not overdo it to avoid TMJ issues.',
    difficulty: 'medium',
    icon: '🍬',
  },
  {
    title: 'Use Retinol or Tretinoin',
    category: 'grooming',
    description: 'Apply a vitamin A derivative at night to speed up cell turnover.',
    benefits: 'The gold standard for anti-aging. Clears acne, reduces hyperpigmentation, and builds collagen to smooth wrinkles.',
    howTo: 'Apply a pea-sized amount to dry skin at night. Start 2x a week and slowly build up. Always wear sunscreen the next day.',
    difficulty: 'medium',
    icon: '🧪',
  },
  {
    title: 'Ice Roller / Cold Water Plunge',
    category: 'grooming',
    description: 'Expose your face to cold temperatures every morning.',
    benefits: 'Constricts blood vessels, immediately de-puffing the face and tightening the skin while waking you up.',
    howTo: 'Keep an ice roller in the freezer or fill a bowl with ice water. Roll for 2-3 minutes or dunk your face for 15 seconds.',
    difficulty: 'easy',
    icon: '🧊',
  },
  {
    title: 'Sleep on a Silk Pillowcase',
    category: 'grooming',
    description: 'Replace cotton pillowcases with silk or satin.',
    benefits: 'Reduces friction which prevents hair breakage, frizz, and sleep wrinkles on the face.',
    howTo: 'Buy a 100% mulberry silk or satin pillowcase. Wash it weekly with a gentle detergent.',
    difficulty: 'easy',
    icon: '🛌',
  },
  {
    title: 'Apply Castor Oil to Brows/Lashes',
    category: 'grooming',
    description: 'Coat eyebrows and eyelashes with cold-pressed castor oil at night.',
    benefits: 'Nourishes the hair follicles, leading to thicker, darker, and longer eyelashes and eyebrows.',
    howTo: 'Use a clean spoolie brush to apply a tiny amount to lashes and brows before sleep. Wash off in the morning.',
    difficulty: 'easy',
    icon: '👁️',
  },
  {
    title: 'Groom and Shape Eyebrows',
    category: 'grooming',
    description: 'Keep eyebrows neat by plucking stray hairs and trimming length.',
    benefits: 'Eyebrows frame the face. Well-groomed brows instantly elevate facial symmetry and attractiveness.',
    howTo: 'Pluck the unibrow and stray hairs below the arch. Brush hairs up and trim any excessively long ones with small scissors.',
    difficulty: 'medium',
    icon: '✂️',
  },
  {
    title: 'Derma Rolling (Hair/Beard)',
    category: 'grooming',
    description: 'Use a microneedle roller on the scalp or beard area 1-2x a week.',
    benefits: 'Stimulates blood flow and collagen production, waking up dormant follicles to promote hair growth.',
    howTo: 'Use a 1.0mm - 1.5mm derma roller. Roll over thinning areas vertically, horizontally, and diagonally. Disinfect before and after.',
    difficulty: 'medium',
    icon: '🪒',
  },
  {
    title: 'Teeth Whitening Routine',
    category: 'grooming',
    description: 'Maintain bright white teeth using strips, special toothpaste, or professional trays.',
    benefits: 'A white smile is one of the most noticeable subconscious indicators of youth and health.',
    howTo: 'Use whitening strips for 30 mins a day for two weeks, or brush with a whitening toothpaste. Avoid coffee/tea right after.',
    difficulty: 'easy',
    icon: '🦷',
  },
  {
    title: 'Apply Lip Balm / Vaseline Overnight',
    category: 'grooming',
    description: 'Slugging the lips with an occlusive before bed.',
    benefits: 'Locks in moisture, heals cracked lips, and keeps lips looking plump, red, and healthy.',
    howTo: 'Apply a hydrating lip balm, then seal it with a layer of Vaseline or Aquaphor before going to sleep.',
    difficulty: 'easy',
    icon: '👄',
  },
  {
    title: 'Moisturize Body Post-Shower',
    category: 'grooming',
    description: 'Apply body lotion while the skin is still damp.',
    benefits: 'Prevents ashy, dry skin, improves skin elasticity, and gives the body a healthy glow.',
    howTo: 'Within 3 minutes of stepping out of the shower, pat dry slightly and rub lotion all over your body.',
    difficulty: 'easy',
    icon: '🧴',
  },
  {
    title: 'Signature Scent / Pulse Points',
    category: 'grooming',
    description: 'Wear a high-quality cologne or perfume daily.',
    benefits: 'Smell is closely tied to memory and attraction. A good scent elevates your perceived attractiveness (halo effect).',
    howTo: 'Apply 2-3 sprays to pulse points: the neck, behind the ears, and wrists. Do not rub wrists together.',
    difficulty: 'easy',
    icon: '✨',
  },
  {
    title: 'Exfoliate Face Twice Weekly',
    category: 'grooming',
    description: 'Use a chemical exfoliant (AHA/BHA) to remove dead skin cells.',
    benefits: 'Unclogs pores, prevents breakouts, and reveals smoother, brighter skin underneath.',
    howTo: 'Apply a salicylic or glycolic acid serum 2x a week on dry skin after cleansing. Skip retinol on these nights.',
    difficulty: 'medium',
    icon: '🧪',
  },
  {
    title: 'Posture Correction (Chin Tucks)',
    category: 'fitness',
    description: 'Perform chin tucks to correct forward head posture ("nerd neck").',
    benefits: 'Improves physical presence, makes you look taller, and enhances the appearance of the jawline.',
    howTo: 'Stand against a wall, pull your head straight back (making a double chin), hold for 5 seconds. Repeat 10 times.',
    difficulty: 'easy',
    icon: '🧍',
  },
  {
    title: 'Neck Training',
    category: 'fitness',
    description: 'Perform neck curls and extensions to thicken the neck.',
    benefits: 'A thicker neck is a highly dimorphic masculine trait that signifies strength and improves facial proportions.',
    howTo: 'Lay on a bench. Use a weight plate on your forehead (with a towel) for neck curls, and back of head for extensions. 3 sets of 15.',
    difficulty: 'hard',
    icon: '🏋️',
  },
  {
    title: 'Cardio for Low Body Fat',
    category: 'fitness',
    description: '30+ minutes of Zone 2 cardio, 3-4 times a week.',
    benefits: 'Burns fat to reveal facial bone structure (hollow cheeks, sharp jawline) and improves vascularity.',
    howTo: 'Jog, cycle, or use the stairmaster at a pace where you can still hold a conversation, but with effort.',
    difficulty: 'hard',
    icon: '🏃',
  },
  {
    title: 'Trim Nails & Cuticle Care',
    category: 'grooming',
    description: 'Cut nails neatly and apply cuticle oil.',
    benefits: 'Clean hands signify good hygiene and attention to detail, which is universally attractive.',
    howTo: 'Clip nails straight across, file the edges, and massage a drop of cuticle oil or lotion into each nail bed.',
    difficulty: 'easy',
    icon: '💅',
  },

  // --- Better Life & Productivity ---
  {
    title: 'Plan Tomorrow Tonight',
    category: 'productivity',
    description: 'Write down your top 3 Most Important Tasks (MITs) for the next day.',
    benefits: 'Eliminates decision fatigue in the morning and ensures you wake up with clear purpose and direction.',
    howTo: 'Before bed, write down the 3 things that, if completed, would make tomorrow a successful day.',
    difficulty: 'easy',
    icon: '📝',
  },
  {
    title: 'No Phone First Hour of the Day',
    category: 'mindfulness',
    description: 'Keep your phone on airplane mode for 60 minutes after waking.',
    benefits: 'Prevents dopamine spikes from social media, reduces anxiety, and keeps you proactive rather than reactive.',
    howTo: 'Buy a traditional alarm clock. Leave your phone charging in another room. Spend the first hour hydrating, stretching, and reading.',
    difficulty: 'hard',
    icon: '📵',
  },
  {
    title: 'Zero Inbox Policy',
    category: 'productivity',
    description: 'Process all emails so your inbox has zero items at the end of the day.',
    benefits: 'Reduces mental clutter, ensures no important communications are missed, and lowers background stress.',
    howTo: 'Apply the 4 Ds: Delete, Delegate, Defer, or Do (if it takes < 2 minutes). Archive emails once processed.',
    difficulty: 'medium',
    icon: '📧',
  },
  {
    title: 'Track All Expenses',
    category: 'better_life',
    description: 'Log every single dollar you spend.',
    benefits: 'Creates financial awareness, highlights unnecessary spending, and is the first step to building wealth.',
    howTo: 'Use an app like YNAB, EveryDollar, or a simple spreadsheet. Log the transaction immediately after purchasing.',
    difficulty: 'medium',
    icon: '💰',
  },
  {
    title: 'Invest 20% of Income',
    category: 'better_life',
    description: 'Automatically route a portion of your paycheck into investments.',
    benefits: 'Takes advantage of compound interest. "Pay yourself first" is the golden rule of financial independence.',
    howTo: 'Set up an auto-transfer to an index fund (like S&P 500) on the day you get paid so you never see the money.',
    difficulty: 'hard',
    icon: '📈',
  },
  {
    title: '15 Mins Morning Sunlight',
    category: 'health',
    description: 'Get outside and view natural sunlight within 30 minutes of waking.',
    benefits: 'Sets your circadian rhythm, boosts cortisol (the good morning kind), and ensures you sleep better at night.',
    howTo: 'Step outside or stand by an open window without sunglasses. Do this for 10-15 minutes (longer if overcast).',
    difficulty: 'easy',
    icon: '🌅',
  },
  {
    title: 'Drink 1 Gallon of Water',
    category: 'health',
    description: 'Consume at least 3-4 liters of water daily.',
    benefits: 'Flushes out toxins, keeps skin clear, prevents water retention (face bloat), and maximizes physical performance.',
    howTo: 'Carry a large reusable bottle. Drink a large glass immediately upon waking. Flavor with lemon or electrolytes if needed.',
    difficulty: 'medium',
    icon: '💧',
  },
  {
    title: 'Eat 1g Protein per lb of Bodyweight',
    category: 'nutrition',
    description: 'Hit a high protein target every day.',
    benefits: 'Crucial for muscle synthesis, keeps you full to prevent snacking, and increases the thermic effect of food.',
    howTo: 'Base every meal around a protein source (eggs, chicken, beef, tofu). Supplement with whey protein if necessary.',
    difficulty: 'medium',
    icon: '🥩',
  },
  {
    title: 'Intermittent Fasting (16:8)',
    category: 'nutrition',
    description: 'Fast for 16 hours, eat all meals within an 8-hour window.',
    benefits: 'Improves insulin sensitivity, promotes autophagy (cellular repair), and makes staying in a caloric deficit easier.',
    howTo: 'Skip breakfast. Eat your first meal at 12:00 PM and finish your last meal by 8:00 PM. Drink black coffee/water during the fast.',
    difficulty: 'medium',
    icon: '⏱️',
  },
  {
    title: 'Read 10 Pages of Non-Fiction',
    category: 'learning',
    description: 'Read self-improvement, business, or educational books daily.',
    benefits: '10 pages a day is roughly 12-15 books a year. You will out-learn 99% of the population.',
    howTo: 'Keep a book on your nightstand or desk. Read immediately upon waking or just before bed.',
    difficulty: 'easy',
    icon: '📚',
  },
  {
    title: 'Learn 1 New Thing Daily',
    category: 'learning',
    description: 'Spend 15 mins actively learning a high-ROI skill.',
    benefits: 'Compounds over time to make you highly valuable. Keeps neuroplasticity high.',
    howTo: 'Practice a language, learn a coding concept, study sales/psychology, or watch an educational documentary.',
    difficulty: 'medium',
    icon: '🧠',
  },
  {
    title: 'Deep Work Blocks (90 mins)',
    category: 'productivity',
    description: 'Work with zero distractions on a cognitively demanding task.',
    benefits: 'Produces massive output. Most people never experience true focus, so doing this gives you a huge competitive advantage.',
    howTo: 'Put phone in another room, block distracting sites, put on noise-canceling headphones, and focus on one single task for 90 mins.',
    difficulty: 'hard',
    icon: '🎧',
  },
  {
    title: 'Limit Social Media to 30 Mins',
    category: 'mindfulness',
    description: 'Use app blockers to restrict scrolling.',
    benefits: 'Reclaims hours of your life, protects dopamine receptors, and reduces comparison/anxiety.',
    howTo: 'Use iOS Screen Time or an app like Freedom to lock out Instagram, TikTok, and Twitter after 30 minutes of total use.',
    difficulty: 'hard',
    icon: '⏳',
  },
  {
    title: '10 Mins Mindfulness Meditation',
    category: 'mindfulness',
    description: 'Sit in silence and observe your thoughts.',
    benefits: 'Increases the gap between stimulus and response, allowing you to react logically rather than emotionally.',
    howTo: 'Sit upright, close your eyes, and focus on the sensation of breathing. When a thought arises, acknowledge it and return to the breath.',
    difficulty: 'medium',
    icon: '🧘',
  },
  {
    title: 'Gratitude Journaling (3 Things)',
    category: 'mindfulness',
    description: 'Write down three specific things you are thankful for.',
    benefits: 'Rewires the brain to look for the positive, increasing baseline happiness and reducing complaints.',
    howTo: 'Be specific. Instead of "family", write "the text my brother sent me today". Do this every night.',
    difficulty: 'easy',
    icon: '🙏',
  },
  {
    title: 'Take Cold Showers',
    category: 'better_life',
    description: 'End your shower with 1-2 minutes of purely cold water.',
    benefits: 'Builds immense discipline, boosts dopamine by 250%, improves circulation, and creates a sense of invincibility to start the day.',
    howTo: 'Take a normal warm shower, then turn the dial all the way to cold. Breathe deeply and endure for 60-120 seconds.',
    difficulty: 'hard',
    icon: '🥶',
  },
  {
    title: 'Weekly Review & Planning',
    category: 'productivity',
    description: 'Spend 1 hour on Sunday reviewing the past week and planning the next.',
    benefits: 'Aligns your daily actions with your long-term goals. Prevents weeks from slipping by unnoticed.',
    howTo: 'Review calendar, check off completed tasks, balance budget, and time-block your goals for the upcoming week.',
    difficulty: 'medium',
    icon: '📅',
  },
  {
    title: 'Call a Friend/Family Member',
    category: 'social',
    description: 'Maintain your social network actively.',
    benefits: 'Strong relationships are the #1 predictor of a long, happy life (Harvard Study of Adult Development).',
    howTo: 'While commuting or taking a walk, dial a friend or parent just to check in for 10 minutes.',
    difficulty: 'easy',
    icon: '📞',
  },
  {
    title: 'Digital Declutter (Weekly)',
    category: 'productivity',
    description: 'Clear out downloads, close tabs, and delete unused apps.',
    benefits: 'Digital minimalism reduces cognitive overload and makes your devices tools rather than traps.',
    howTo: 'Empty the trash bin, organize desktop files into folders, and delete 1 app you haven\'t used in a month.',
    difficulty: 'easy',
    icon: '🧹',
  },
  {
    title: 'Cook 1 Meal at Home',
    category: 'better_life',
    description: 'Prepare a healthy meal from scratch.',
    benefits: 'Saves money, teaches a high-value survival/social skill, and gives you absolute control over macros and ingredients.',
    howTo: 'Find a simple recipe (e.g., steak and rice, or chicken stir-fry) and master it. Buy whole foods.',
    difficulty: 'medium',
    icon: '🍳',
  },
  {
    title: 'Drink Green Tea / Matcha',
    category: 'health',
    description: 'Replace one coffee with high-quality green tea.',
    benefits: 'Loaded with EGCG antioxidants for skin health, and L-theanine which provides a calm, jitter-free focus.',
    howTo: 'Brew matcha or green tea in the mid-morning instead of a second cup of coffee.',
    difficulty: 'easy',
    icon: '🍵',
  },
  {
    title: 'Write Down Ideas (Idea Journal)',
    category: 'productivity',
    description: 'Carry a pocket notebook and write down 10 ideas a day.',
    benefits: 'Exercises your "idea muscle", making you more creative and prone to spotting opportunities.',
    howTo: 'Write down 10 ideas for businesses, videos, solutions to a problem, or gifts. They don\'t have to be good.',
    difficulty: 'medium',
    icon: '💡',
  },
  {
    title: 'No Screens 1 Hour Before Bed',
    category: 'sleep',
    description: 'Stop looking at phones, TVs, and monitors 60 mins before sleep.',
    benefits: 'Prevents blue light from destroying melatonin production, ensuring deep REM and restorative sleep.',
    howTo: 'Use this hour to read, stretch, journal, or chat. Use dim, warm lighting in your house.',
    difficulty: 'medium',
    icon: '🌙',
  },
  {
    title: 'Declutter 1 Small Area',
    category: 'better_life',
    description: 'Organize one drawer, desk, or corner of a room.',
    benefits: 'A clean environment equals a clear mind. Small daily decluttering prevents massive weekend chores.',
    howTo: 'Set a 5-minute timer. Throw away trash, put items in their designated spots, and wipe down the surface.',
    difficulty: 'easy',
    icon: '🗑️',
  },
  {
    title: 'Listen to a Podcast/Audiobook',
    category: 'learning',
    description: 'Turn "dead time" (commuting, chores) into learning time.',
    benefits: 'Dramatically increases your educational intake without requiring extra free time.',
    howTo: 'Put on a high-value podcast (Huberman, Lex Fridman, My First Million) while doing dishes or driving.',
    difficulty: 'easy',
    icon: '🎧',
  },
  {
    title: 'Practice Public Speaking/Vocab',
    category: 'learning',
    description: 'Record yourself speaking or consciously use a new word.',
    benefits: 'Articulate people are perceived as highly intelligent and competent. It\'s a cheat code for life.',
    howTo: 'Look up a "word of the day" and use it in a conversation, or record a 1-minute video explaining a concept and review it.',
    difficulty: 'medium',
    icon: '🗣️',
  },
  {
    title: 'Say "No" to Unnecessary Commitments',
    category: 'better_life',
    description: 'Decline an invitation or request that doesn\'t align with your goals.',
    benefits: 'Protects your most valuable asset: Time. Helps you avoid burnout and focus on what matters.',
    howTo: 'Use a polite but firm template: "Thank you for thinking of me, but I don\'t have the bandwidth for this right now."',
    difficulty: 'hard',
    icon: '🛡️',
  },
  {
    title: '8 Hours of Sleep on Back',
    category: 'grooming',
    description: 'Sleep on your back for 7-8 hours.',
    benefits: 'Sleeping on your back prevents facial asymmetry and wrinkles caused by smashing your face into a pillow for hours.',
    howTo: 'Use a cervical pillow to cradle your neck. Put a pillow under your knees to take pressure off your lower back.',
    difficulty: 'hard',
    icon: '🛌',
  },
  {
    title: 'Take the Stairs',
    category: 'fitness',
    description: 'Always opt for stairs over elevators or escalators.',
    benefits: 'Sneaks extra NEAT (Non-Exercise Activity Thermogenesis) into your day, burning extra calories effortlessly.',
    howTo: 'Unless it\'s over 5 flights and you are in a rush, take the stairs. It builds leg strength and cardio.',
    difficulty: 'easy',
    icon: '🚶‍♂️',
  },
  {
    title: 'Stretching / Yoga (15 mins)',
    category: 'fitness',
    description: 'Follow a mobility or yoga routine.',
    benefits: 'Prevents injuries, fixes posture, and releases tension held in the hips and shoulders from sitting.',
    howTo: 'Follow a 15-minute YouTube video for mobility or yoga first thing in the morning or post-workout.',
    difficulty: 'medium',
    icon: '🧘‍♂️',
  }
];

const defaultShopItems = [
  // Avatars
  { name: 'Cosmic Voyager', type: 'avatar', description: 'A space-themed avatar with starry vibes', price: 100, rarity: 'common', imageUrl: 'avatar-cosmic' },
  { name: 'Neon Samurai', type: 'avatar', description: 'Cyberpunk-inspired warrior avatar', price: 200, rarity: 'rare', imageUrl: 'avatar-samurai' },
  { name: 'Crystal Guardian', type: 'avatar', description: 'A mystical guardian encased in crystals', price: 350, rarity: 'rare', imageUrl: 'avatar-crystal' },
  { name: 'Phoenix Rising', type: 'avatar', description: 'A legendary phoenix avatar wreathed in flames', price: 500, rarity: 'epic', imageUrl: 'avatar-phoenix' },
  { name: 'Shadow Monarch', type: 'avatar', description: 'An enigmatic ruler of shadows', price: 750, rarity: 'epic', imageUrl: 'avatar-shadow' },
  { name: 'Celestial Dragon', type: 'avatar', description: 'The rarest avatar — a divine dragon of legend', price: 1500, rarity: 'legendary', imageUrl: 'avatar-dragon' },

  // Themes
  { name: 'Ocean Depths', type: 'theme', description: 'Deep blue and teal color scheme', price: 150, rarity: 'common', previewData: { primary: '#0ea5e9', secondary: '#06b6d4', bg: '#0c1929' } },
  { name: 'Forest Mist', type: 'theme', description: 'Calming green and emerald tones', price: 150, rarity: 'common', previewData: { primary: '#10b981', secondary: '#34d399', bg: '#0c1f17' } },
  { name: 'Sunset Blaze', type: 'theme', description: 'Warm orange and crimson gradients', price: 300, rarity: 'rare', previewData: { primary: '#f97316', secondary: '#ef4444', bg: '#1a0f0a' } },
  { name: 'Aurora Borealis', type: 'theme', description: 'Ethereal green-to-purple northern lights', price: 500, rarity: 'epic', previewData: { primary: '#22d3ee', secondary: '#a855f7', bg: '#0a1520' } },
  { name: 'Golden Dynasty', type: 'theme', description: 'Luxurious gold and dark amber accents', price: 1000, rarity: 'legendary', previewData: { primary: '#f59e0b', secondary: '#d97706', bg: '#1a1508' } },

  // Borders
  { name: 'Gradient Ring', type: 'border', description: 'A smooth gradient border around your avatar', price: 75, rarity: 'common' },
  { name: 'Pulsing Glow', type: 'border', description: 'Your avatar border pulses with soft light', price: 200, rarity: 'rare' },
  { name: 'Lightning Arc', type: 'border', description: 'Electric sparks dance around your profile', price: 400, rarity: 'epic' },
  { name: 'Cosmic Orbit', type: 'border', description: 'Tiny stars orbit your avatar in real-time', price: 800, rarity: 'legendary' },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Force clear habits and re-seed
    await Habit.deleteMany({});
    console.log('🗑️  Cleared existing habits');
    
    await Habit.insertMany(defaultHabits);
    console.log(`✅ Seeded ${defaultHabits.length} default habits`);

    // Seed Shop Items
    const existingItems = await ShopItem.countDocuments();
    if (existingItems === 0) {
      await ShopItem.insertMany(defaultShopItems);
      console.log(`✅ Seeded ${defaultShopItems.length} shop items`);
    } else {
      console.log(`ℹ️  ${existingItems} shop items already exist, skipping seed`);
    }

    console.log('\n🎉 Seed complete!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed error:', error);
    process.exit(1);
  }
}

seed();
